### DISCUSSION TITLE
Home Assistant Lovelace cards for snapcast

### DISCUSSION THREAD

**Discussion by artmg** [snapcast/snapcast#1039] [Show and tell]
I created this 'discussion' to answer a part of a subquestion that was going quite off topic for the original discussion #828 

This may be out of date now, but here is an example of a Home Assistant front end to:

* Switch sources on the snapcast server group
* Fade the volume on individual clients in the group

To answer @tobulli 's question, I have **not** found an alternative to the group changing name when its membership gets altered, so I just _update the group name_ each time, as you can see from the times I have changed it...

## ui-lovelace.yaml

```yaml
  - type: custom:mini-media-player
    entity: media_player.snapcast_group_87691189_0fdc_6421_d698_344d211695b0
    # entity: media_player.snapcast_group_6beba9a6_4708_b98b_27f7_50ed7e7b97a3 
    # entity: media_player.snapcast_group_64c55b97_2c52_d839_7eeb_a15916beb353
    # entity: media_player.snapcast_client_b8_27_eb_94_76_8e_2
    name: MySnapServer music source
    icon: mdi:router-wireless-settings
    hide:
      controls: true
      power:    true
      volume:   true
      mute:     true
  # snapcast faders - should these be grouped?
  - type: entities
    title: Room Faders
    icon: mdi:cast-audio
    show_header_toggle: false
    entities:
    - type: custom:mini-media-player
      entity: media_player.snapcast_client_b8_27_eb_94_76_8e_2
      # Fader Room1
      group: true
      hide:
        controls: true
        icon: true
        power: true
        source: true
    - type: custom:mini-media-player
      entity: media_player.snapcast_client_b8_27_eb_9d_79_90
      # Fader Room2
      group: true
      hide:
        controls: true
        icon: true
        power: true
        source: true
    - type: custom:mini-media-player
      entity: media_player.snapcast_client_b8_27_eb_c8_1c_ce_2
      # Fader Room3
      group: true
      hide:
        controls: true
        icon: true
        power: true
        source: true
```

I am not aware of any way to persist group references when changes are made, but we'd love to be enlightened if you know.
